/**
 * dodatci/raznolikost.js — pojedinačno napisana pitanja za teme koje su imale
 * premalo RAZLIČITIH VRSTA pitanja (obitelji). Svako pitanje je svoja obitelj,
 * pa kviz i u 20. igranju može složiti sedam različitih zadataka.
 */
const { izbor, tocnoNetocno } = require('./pomocno');

/** [pitanje, točno, [ometači]] ili [pitanje, true/false] — svako pitanje svoja obitelj. */
const zasebno = (redovi, tezina = 2) => redovi.map((r) => {
  const q = typeof r[1] === 'boolean' ? tocnoNetocno(r[0], r[1], tezina, r[2] || '') : izbor(r[0], r[1], r[2], tezina, r[3] || '');
  return { ...q, obitelj: `pitanje:${r[0]}` };
});

const DIGITALNI_12 = [
  ['Što trebaš učiniti prije nego što uključiš tablet koji nije tvoj?', 'pitati vlasnika smiješ li', ['uzeti ga bez pitanja', 'sakriti ga', 'dati ga mlađem bratu']],
  ['Gdje je najbolje držati tablet dok ga ne koristiš?', 'na stolu ili polici, daleko od vode', ['na podu u hodniku', 'u kadi', 'na rubu prozora']],
  ['Što znači kad baterija na zaslonu pokazuje crvenu boju?', 'baterija je skoro prazna', ['uređaj je nov', 'uređaj je pun', 'internet je spor']],
  ['Kojom tipkom brišemo slovo koje smo krivo napisali?', 'Backspace', ['Enter', 'Shift', 'razmaknica']],
  ['Što je ikona na zaslonu?', 'mala slika koja otvara program', ['tipka na tipkovnici', 'kabel za punjenje', 'vrsta pisača']],
  ['Što radimo kad dvaput brzo kliknemo mišem na ikonu?', 'otvaramo program ili datoteku', ['gasimo računalo', 'punimo bateriju', 'brišemo sve']],
  ['Kako pravilno isključujemo računalo?', 'odaberemo Isključi u izborniku', ['izvučemo kabel iz zida', 'polijemo ga vodom', 'zatvorimo poklopac silom']],
  ['Koji je od ovih uređaja prijenosan?', 'tablet', ['veliki pisač', 'stolno računalo', 'hladnjak']],
  ['Kako zovemo glazbu, slike i igre koje dobivamo na računalu?', 'digitalni sadržaj', ['drvene igračke', 'tiskane knjige', 'društvene igre']],
  ['Što je dobro učiniti ako ti se pojavi prozor koji traži da nešto kupiš?', 'pozvati odraslu osobu', ['kliknuti „Kupi”', 'upisati mamin broj kartice', 'zatvoriti oči i kliknuti bilo gdje']],
  ['Zašto ne jedemo uz tipkovnicu?', 'mrvice i tekućina mogu je pokvariti', ['tipkovnica se ljuti', 'hrana postaje digitalna', 'zaslon se ugasi']],
  ['Što pomaže očima kad dugo gledamo u zaslon?', 'kratka pauza i pogled u daljinu', ['gledanje izbliza', 'mrak u sobi', 'treptanje bez prestanka']],
  ['Je li u redu snimiti učiteljicu mobitelom bez njezina pitanja?', false],
  ['Može li računalo raditi bez struje ili baterije?', false],
  ['Je li miš ovdje uređaj kojim pomičemo strelicu?', true],
  ['Treba li tablet čistiti mekanom suhom krpicom?', true],
  ['Smiješ li slati poruke nepoznatima iz igrice?', false],
  ['Treba li uređaj isključiti kad ideš spavati?', true],
  ['Mogu li se slike na internetu kopirati i proslijediti dalje?', true],
  ['Je li dobro igrati igrice dok hodaš ulicom?', false],
  ['Može li se pokvariti zaslon ako pritišćemo jako olovkom?', true],
  ['Trebaš li se smiriti i reći odraslom ako slučajno nešto izbrišeš?', true],
];
const KUTOVI = [
  ['Kako zovemo kut manji od pravoga?', 'šiljasti kut', ['tupi kut', 'ispruženi kut', 'puni kut']],
  ['Kako zovemo kut veći od pravoga, a manji od ispruženoga?', 'tupi kut', ['šiljasti kut', 'pravi kut', 'puni kut']],
  ['Koliko pravih kutova ima kvadrat?', '4', ['2', '3', '1']],
  ['Koliko pravih kutova čini ispruženi kut?', '2', ['1', '3', '4']],
  ['Koliko pravih kutova čini puni kut?', '4', ['2', '3', '1']],
  ['Koji kut zatvaraju kazaljke sata u 3 sata?', 'pravi kut', ['šiljasti kut', 'ispruženi kut', 'tupi kut']],
  ['Koji kut zatvaraju kazaljke sata u 6 sati?', 'ispruženi kut', ['pravi kut', 'šiljasti kut', 'tupi kut']],
  ['Koji kut zatvaraju kazaljke sata u 1 sat?', 'šiljasti kut', ['pravi kut', 'tupi kut', 'ispruženi kut']],
  ['Koji kut zatvaraju kazaljke sata u 5 sati?', 'tupi kut', ['šiljasti kut', 'pravi kut', 'puni kut']],
  ['Kako zovemo zajedničku točku krakova kuta?', 'vrh kuta', ['krak', 'stranica', 'središte']],
  ['Kako zovemo polupravce koji omeđuju kut?', 'krakovi kuta', ['vrhovi kuta', 'stranice kvadrata', 'dužine trokuta']],
  ['Kojim priborom najlakše provjerimo je li kut pravi?', 'geometrijskim trokutom', ['šestarom', 'gumicom', 'kistom']],
  ['Koji kut ima kut prozora u učionici?', 'pravi kut', ['šiljasti kut', 'tupi kut', 'ispruženi kut']],
  ['Koliko kutova ima trokut?', '3', ['2', '4', '6']],
  ['Kakve kutove ima pravokutnik?', 'sve prave kutove', ['sve šiljaste kutove', 'sve tupe kutove', 'nijedan kut']],
  ['Kakve kutove zatvaraju okomiti pravci?', 'prave kutove', ['šiljaste kutove', 'tupe kutove', 'nikakve']],
  ['Kakav je kut vrha krova kuće na crtežu ako je uži od ugla bilježnice?', 'šiljasti kut', ['tupi kut', 'pravi kut', 'puni kut']],
  ['Je li pravi kut veći od šiljastoga?', true],
  ['Ima li ispruženi kut krakove na istom pravcu?', true],
  ['Je li tupi kut manji od pravoga?', false],
  ['Može li trokut imati jedan pravi kut?', true],
  ['Ima li krug kutove?', false],
  ['Označavamo li vrh kuta velikim tiskanim slovom?', true],
];
const KVADAR = [
  ['Koje tijelo podsjeća na kockicu šećera?', 'kocka', ['kvadar', 'valjak', 'kugla']],
  ['Koliko je bridova kocke jednake duljine?', 'svih 12', ['samo 4', 'samo 6', 'nijedan']],
  ['Koliko različitih duljina bridova može imati kvadar?', 'najviše 3', ['najviše 1', 'najviše 12', 'najviše 8']],
  ['Koje tijelo dobijemo kad složimo dvije jednake kocke jednu uz drugu?', 'kvadar', ['kocku', 'valjak', 'piramidu']],
  ['Koliko malih kocaka treba za veću kocku s bridom od 2 male kocke?', '8', ['4', '6', '12']],
  ['Što na kocki za igru pokazuju točkice na plohama?', 'brojeve od 1 do 6', ['brojeve od 1 do 12', 'samo parne brojeve', 'slova']],
  ['Koliko vrhova ima jedna ploha kocke?', '4', ['3', '6', '8']],
  ['Koliko bridova ima jedna ploha kvadra?', '4', ['3', '6', '12']],
  ['Kakav je lik ploha kocke?', 'kvadrat', ['krug', 'trokut', 'peterokut']],
  ['Koji od ovih predmeta nema oblik kvadra?', 'lopta', ['cigla', 'kutija za cipele', 'knjiga']],
  ['Možemo li kvadar složiti od 6 pravokutnika?', true],
  ['Ima li kocka bridove različitih duljina?', false],
  ['Može li se kocka stabilno položiti na bilo koju plohu?', true],
  ['Je li mreža kocke sastavljena od trokuta?', false],
  ['Imaju li kocka i kvadar jednak broj vrhova?', true],
];
const UVJETI = [
  ['Zašto na golom kamenjaru uz more raste malo biljaka?', 'ondje ima vrlo malo vode i tla', ['ondje nema svjetlosti', 'ondje je previše hladno', 'ondje nema zraka']],
  ['Zašto na vrhovima visokih planina ima malo biljaka?', 'ondje je hladno, a tlo je tanko', ['ondje je previše vode', 'ondje je previše toplo', 'ondje nema svjetla']],
  ['Što se događa s biljkom kad dugo nema vode?', 'vene i suši se', ['brže raste', 'postane plava', 'cvjeta više']],
  ['Zašto se u šumi pri tlu nalazi manje biljaka koje trebaju mnogo svjetla?', 'krošnje zaklanjaju svjetlost', ['ondje nema zraka', 'tlo je preslano', 'ondje nema vode']],
  ['Zašto ribe ugibaju kad se voda jako onečisti?', 'u vodi ima premalo kisika i ima otrova', ['voda postane preslatka', 'ribama postane dosadno', 'voda postane prozirna']],
  ['Što se događa sa životinjama kad ljudi posijeku šumu?', 'gube dom i hranu', ['dobivaju veći dom', 'ništa', 'postaju domaće']],
  ['Koji je uvjet života najvažniji za disanje?', 'zrak', ['tlo', 'svjetlost', 'kamenje']],
  ['Zašto žabe žive blizu vode?', 'jaja polažu u vodu, a koža im mora biti vlažna', ['ne vole sunce', 'u vodi spavaju zimi sve vrste', 'ne mogu skakati']],
  ['Zašto lastavice u jesen odlaze?', 'zimi kod nas nema kukaca kojima se hrane', ['ne vole snijeg na krovovima', 'idu na školovanje', 'bježe od ljudi']],
  ['Što biljci daje tlo?', 'vodu s otopljenim hranjivim tvarima i oslonac', ['svjetlost', 'toplinu sunca', 'kisik iz zraka']],
  ['Kako ljudi mogu pomoći životinjama zimi?', 'postaviti hranilice za ptice', ['rušiti gnijezda', 'buditi ježeve', 'loviti ptice']],
  ['Zašto je važno da u rijekama bude čista voda?', 'o njoj ovise biljke, životinje i ljudi', ['da bude ljepše boje', 'da brže teče', 'nije važno']],
  ['Može li sjemenka proklijati bez topline?', false],
  ['Treba li životinjama sklonište?', true],
  ['Prilagođavaju li se živa bića uvjetima u kojima žive?', true],
  ['Može li riba živjeti u vodi bez kisika?', false],
  ['Je li svjetlost potrebna biljkama za stvaranje hrane?', true],
  ['Žive li u moru i biljke i životinje?', true],
];
const DOMOVINA = [
  ['Koji je hrvatski otok poznat po čipki?', 'Pag', ['Krk', 'Vis', 'Lastovo']],
  ['Kako se zove poznati slap na rijeci Krki?', 'Skradinski buk', ['Veliki slap', 'Rastoke', 'Gubavica']],
  ['Koja je rijeka u Dubrovačko-neretvanskoj županiji poznata po mandarinama u dolini?', 'Neretva', ['Sava', 'Drava', 'Kupa']],
  ['Kako se zove trg u središtu Zagreba?', 'Trg bana Josipa Jelačića', ['Trg Republike', 'Pjaca', 'Korzo']],
  ['Na kojem se trgu u Zagrebu nalaze Sabor i Vlada?', 'Markov trg', ['Trg bana Jelačića', 'Britanski trg', 'Trg žrtava fašizma']],
  ['Koje je boje polje u gornjem lijevom kutu šahovnice na grbu?', 'crveno', ['bijelo', 'plavo', 'zeleno']],
  ['Koliko manjih grbova čini krunu na hrvatskom grbu?', '5', ['3', '7', '10']],
  ['Kako se zove skupina otoka koja je nacionalni park, a ima mnogo golih otočića?', 'Kornati', ['Brijuni', 'Elafiti', 'Lastovo']],
  ['Koji grad zovu „grad heroj” zbog obrane u Domovinskom ratu?', 'Vukovar', ['Pula', 'Varaždin', 'Zadar']],
  ['Kada je Hrvatska postala članica Europske unije?', '2013. godine', ['1991. godine', '2000. godine', '2023. godine']],
  ['Je li Zagreb najveći grad u Hrvatskoj?', true],
  ['Ima li Hrvatska više od tisuću otoka, otočića i hridi?', true],
  ['Je li Dinara najviša planina Hrvatske?', true],
  ['Teče li Dunav kroz Zagreb?', false],
  ['Nalazi li se Pula u Istri?', true],
  ['Je li Split glavni grad Hrvatske?', false],
];
const JA_I_DRUGI = [
  ['Prijatelj ti priznaje da je razbio tvoju igračku i ispričava se. Što je lijepo učiniti?', 'prihvatiti ispriku', ['vikati na njega tjedan dana', 'razbiti njegovu igračku', 'reći svima da je loš']],
  ['Što znači biti dobar prijatelj?', 'pomagati, slušati i poštovati drugoga', ['uvijek pobjeđivati', 'naređivati drugima', 'skrivati tuđe stvari']],
  ['Što možeš učiniti kad se osjećaš usamljeno?', 'razgovarati s nekim kome vjeruješ', ['zatvoriti se u ormar', 'ljutiti se na sve', 'ne jesti']],
  ['Kako se zove osjećaj kad se nečemu veselimo unaprijed?', 'radost iščekivanja', ['ljutnja', 'strah', 'dosada']],
  ['Kako pokazujemo poštovanje prema starijima?', 'pozdravimo ih i pustimo da sjednu', ['ne gledamo ih', 'rugamo im se', 'guramo se ispred njih']],
  ['Učiteljica kaže da su svi ljudi jednako vrijedni. Što to znači?', 'nitko nije vrjedniji zbog izgleda, porijekla ili bogatstva', ['vrjedniji su oni koji imaju više igračaka', 'vrjedniji su viši ljudi', 'vrjedniji su samo odrasli']],
  ['Prijateljica nosi naočale i netko joj se ruga. Što ćeš učiniti?', 'stati uz nju i reći da ruganje nije u redu', ['smijati se s ostalima', 'šutjeti i otići', 'i sam se rugati']],
  ['Što je razredni dogovor (pravila razreda)?', 'pravila koja zajedno dogovorimo i poštujemo', ['zabrana igre', 'popis kazni za učiteljicu', 'tajna jednog učenika']],
  ['Kako možeš razveseliti baku koja je sama?', 'posjetiti je ili nazvati', ['zaboraviti na nju', 'poslati joj ružnu poruku', 'sakriti joj naočale']],
  ['Kad se dvoje svađa oko igre, što je pošteno?', 'izmjenjivati se ili igrati zajedno', ['pustiti da jači uzme sve', 'baciti igru', 'tužiti bez razgovora']],
  ['Je li u redu plakati kad smo tužni?', true],
  ['Smijemo li reći „ne” kad nas netko nagovara na nešto opasno?', true],
  ['Je li važno slušati kad drugi govori?', true],
  ['Je li u redu govoriti loše o nekome iza leđa?', false],
  ['Imaju li svi ljudi pravo na svoje mišljenje?', true],
  ['Je li pomaganje drugima znak slabosti?', false],
];
const PROMET = [
  ['Zašto biciklist na cesti treba nositi kacigu?', 'štiti glavu pri padu', ['da se ne smoči kosa', 'da bude brži', 'da ga vozači ne vide']],
  ['Kako biciklisti voze u skupini po cesti?', 'jedan iza drugoga', ['trojica jedan pokraj drugoga', 'kako god žele', 'u paru držeći se za ruke']],
  ['Što biciklist mora učiniti prije skretanja?', 'pogledati unatrag i pokazati rukom smjer', ['zažmiriti', 'ubrzati bez gledanja', 'zazvoniti i skrenuti bez gledanja']],
  ['Kako se zove dio ceste rezerviran samo za bicikle?', 'biciklistička staza', ['pješački prijelaz', 'parkiralište', 'autocesta']],
  ['Smiju li bicikli voziti autocestom?', 'ne, nikada', ['da, uvijek', 'samo noću', 'samo nedjeljom']],
  ['Zašto noću biciklist mora imati upaljena svjetla?', 'da vidi put i da ga drugi vide', ['da ne zaspi', 'da bude ljepši', 'da štedi bateriju']],
  ['Što trebaš učiniti ako ti na biciklu ne rade kočnice?', 'ne voziti dok ih odrasla osoba ne popravi', ['voziti polako nizbrdo', 'kočiti nogama', 'voziti samo ujutro']],
  ['Gdje je najsigurnije učiti voziti bicikl?', 'na igralištu ili u parku, daleko od prometa', ['na raskrižju', 'na autocesti', 'na tramvajskoj pruzi']],
  ['Kako se ponašamo kad prolazi vozilo hitne pomoći s rotirkom?', 'sklonimo se i propustimo ga', ['trčimo za njim', 'stanemo na sredinu ceste', 'ne obraćamo pozornost']],
  ['Koja je boja prometnih znakova koji upozoravaju na opasnost (rub trokuta)?', 'crvena', ['plava', 'zelena', 'smeđa']],
  ['Smije li biciklist voziti s otvorenim kišobranom u ruci?', false],
  ['Treba li sjedalo bicikla podesiti prema visini djeteta?', true],
  ['Smije li biciklist prevoziti teret koji mu zaklanja pogled?', false],
  ['Treba li biciklist pustiti pješake da prijeđu na pješačkom prijelazu?', true],
  ['Je li reflektirajući prsluk koristan danju i noću?', true],
  ['Smije li biciklist voziti u suprotnom smjeru jednosmjerne ulice?', false],
];

module.exports = {
  genDigitalniSvijet1: () => zasebno(DIGITALNI_12, 1), genDigitalniSvijet2: () => zasebno(DIGITALNI_12, 1),
  genGeometrijaKutovi: () => zasebno(KUTOVI, 2), genKvaderKocka: () => zasebno(KVADAR, 2),
  genUvjetiZivota: () => zasebno(UVJETI, 2), genHrvatskaDomovina: () => zasebno(DOMOVINA, 2),
  genJaIDrugi1: () => zasebno(JA_I_DRUGI, 1), genJaIDrugi2: () => zasebno(JA_I_DRUGI, 1), genJaIDrugi3: () => zasebno(JA_I_DRUGI, 2), genJaIDrugi4: () => zasebno(JA_I_DRUGI, 2),
  genPromet3: () => zasebno(PROMET, 2), genPromet4: () => zasebno(PROMET, 2),
};
